version: '2.1'

volumes:
  netdatacache:
  netdatalib:
services:
  netdata:
    build: ./netdata
    privileged: true
    ports:
      - '19999:19999'
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    labels:
      io.balena.features.balena-socket: 1
      io.balena.features.procfs: 1
      io.balena.features.supervisor-api: 1
      io.balena.features.sysfs: 1
    volumes:
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata